<?php

return [
    'port' => 4007,
    'organization_name' => 'Grand Lodge of Alpha',
    'contact_person' => 'Alice Anderson',
    'contact_phone' => '+1-555-0001',
    'share_my_organization' => true,
    'trust_threshold' => 1,
    'members' => [
        [
            'member_number' => 'ALPHA-001',
            'first_name' => 'John',
            'middle_name' => 'Robert',
            'last_name' => 'Smith',
            'birthdate' => '1975-03-15',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 20,
            'email' => 'john.smith@example.com',
            'phone' => '+1-555-1001',
            'address' => [
                'line1' => '123 Main Street',
                'city' => 'Springfield',
                'state' => 'IL',
                'postal_code' => '62701',
                'country' => 'US',
            ],
            'affiliations' => [
                [
                    'group_identifier' => 'ALPHA-LODGE-001',
                    'group_name' => 'Springfield Lodge No. 1',
                    'role' => 'Past Master',
                    'status' => 'Active',
                    'membership_start' => '2005-06-15',
                ],
            ],
            'life_cycle_events' => [
                ['event_type' => 'Initiated', 'event_date' => '2004-03-15'],
                ['event_type' => 'Passed', 'event_date' => '2004-06-20'],
                ['event_type' => 'Raised', 'event_date' => '2004-09-18'],
            ],
        ],
        [
            'member_number' => 'ALPHA-002',
            'first_name' => 'Michael',
            'last_name' => 'Johnson',
            'birthdate' => '1982-07-22',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 15,
            'email' => 'michael.johnson@example.com',
            'phone' => '+1-555-1002',
            'affiliations' => [
                [
                    'group_identifier' => 'ALPHA-LODGE-002',
                    'group_name' => 'Capital City Lodge No. 2',
                    'role' => 'Senior Warden',
                    'status' => 'Active',
                ],
            ],
        ],
        [
            'member_number' => 'ALPHA-003',
            'first_name' => 'David',
            'last_name' => 'Williams',
            'birthdate' => '1968-11-08',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => false,
            'years_in_good_standing' => 0,
            'email' => 'david.williams@example.com',
            'affiliations' => [
                [
                    'group_identifier' => 'ALPHA-LODGE-001',
                    'group_name' => 'Springfield Lodge No. 1',
                    'role' => 'Member',
                    'status' => 'Suspended',
                ],
            ],
        ],
        [
            'member_number' => 'ALPHA-004',
            'first_name' => 'Christopher',
            'last_name' => 'Brown',
            'birthdate' => '1990-04-30',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 5,
            'email' => 'chris.brown@example.com',
            'affiliations' => [
                [
                    'group_identifier' => 'ALPHA-LODGE-003',
                    'group_name' => 'Riverside Lodge No. 3',
                    'role' => 'Junior Deacon',
                    'status' => 'Active',
                ],
            ],
        ],
    ],
];
