<?php

return [
    'port' => 4009,
    'organization_name' => 'Grand Lodge of Gamma',
    'contact_person' => 'Carol Chen',
    'contact_phone' => '+1-555-0003',
    'share_my_organization' => true,
    'trust_threshold' => 1,
    'members' => [
        [
            'member_number' => 'GAMMA-001',
            'first_name' => 'Daniel',
            'middle_name' => 'Lee',
            'last_name' => 'Martinez',
            'birthdate' => '1965-08-20',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 30,
            'email' => 'daniel.martinez@example.com',
            'phone' => '+1-555-3001',
            'address' => [
                'line1' => '789 Pine Road',
                'city' => 'Denver',
                'state' => 'CO',
                'postal_code' => '80202',
                'country' => 'US',
            ],
            'affiliations' => [
                [
                    'group_identifier' => 'GAMMA-LODGE-001',
                    'group_name' => 'Denver Lodge No. 100',
                    'role' => 'Past Grand Master',
                    'status' => 'Active',
                    'membership_start' => '1994-04-01',
                ],
            ],
            'life_cycle_events' => [
                ['event_type' => 'Initiated', 'event_date' => '1993-01-15'],
                ['event_type' => 'Passed', 'event_date' => '1993-04-20'],
                ['event_type' => 'Raised', 'event_date' => '1993-07-17'],
            ],
        ],
        [
            'member_number' => 'GAMMA-002',
            'first_name' => 'Joseph',
            'last_name' => 'Garcia',
            'birthdate' => '1980-03-28',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 18,
            'email' => 'joseph.garcia@example.com',
            'phone' => '+1-555-3002',
            'affiliations' => [
                [
                    'group_identifier' => 'GAMMA-LODGE-002',
                    'group_name' => 'Boulder Lodge No. 200',
                    'role' => 'Treasurer',
                    'status' => 'Active',
                ],
            ],
        ],
        [
            'member_number' => 'GAMMA-003',
            'first_name' => 'Charles',
            'last_name' => 'Rodriguez',
            'birthdate' => '1988-10-14',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 8,
            'email' => 'charles.rodriguez@example.com',
            'affiliations' => [
                [
                    'group_identifier' => 'GAMMA-LODGE-001',
                    'group_name' => 'Denver Lodge No. 100',
                    'role' => 'Junior Warden',
                    'status' => 'Active',
                ],
            ],
        ],
        [
            'member_number' => 'GAMMA-004',
            'first_name' => 'Thomas',
            'last_name' => 'Lopez',
            'birthdate' => '1995-07-07',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 2,
            'email' => 'thomas.lopez@example.com',
            'affiliations' => [
                [
                    'group_identifier' => 'GAMMA-LODGE-003',
                    'group_name' => 'Aspen Lodge No. 300',
                    'role' => 'Entered Apprentice',
                    'status' => 'Active',
                ],
            ],
        ],
    ],
];
