<?php

return [
    'port' => 4008,
    'organization_name' => 'Grand Lodge of Beta',
    'contact_person' => 'Bob Baker',
    'contact_phone' => '+1-555-0002',
    'share_my_organization' => true,
    'trust_threshold' => 1,
    'members' => [
        [
            'member_number' => 'BETA-001',
            'first_name' => 'James',
            'middle_name' => 'Edward',
            'last_name' => 'Wilson',
            'birthdate' => '1970-01-25',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 25,
            'email' => 'james.wilson@example.com',
            'phone' => '+1-555-2001',
            'address' => [
                'line1' => '456 Oak Avenue',
                'city' => 'Riverside',
                'state' => 'CA',
                'postal_code' => '92501',
                'country' => 'US',
            ],
            'affiliations' => [
                [
                    'group_identifier' => 'BETA-LODGE-001',
                    'group_name' => 'Riverside Lodge No. 10',
                    'role' => 'Worshipful Master',
                    'status' => 'Active',
                    'membership_start' => '1999-01-10',
                ],
            ],
            'life_cycle_events' => [
                ['event_type' => 'Initiated', 'event_date' => '1998-02-14'],
                ['event_type' => 'Passed', 'event_date' => '1998-05-16'],
                ['event_type' => 'Raised', 'event_date' => '1998-08-22'],
            ],
        ],
        [
            'member_number' => 'BETA-002',
            'first_name' => 'Robert',
            'last_name' => 'Taylor',
            'birthdate' => '1985-09-12',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 10,
            'email' => 'robert.taylor@example.com',
            'phone' => '+1-555-2002',
            'affiliations' => [
                [
                    'group_identifier' => 'BETA-LODGE-002',
                    'group_name' => 'Mountain View Lodge No. 20',
                    'role' => 'Secretary',
                    'status' => 'Active',
                ],
            ],
        ],
        [
            'member_number' => 'BETA-003',
            'first_name' => 'William',
            'last_name' => 'Anderson',
            'birthdate' => '1978-06-05',
            'status' => 'Inactive',
            'is_active' => false,
            'good_standing' => false,
            'years_in_good_standing' => 0,
            'email' => 'william.anderson@example.com',
            'affiliations' => [
                [
                    'group_identifier' => 'BETA-LODGE-001',
                    'group_name' => 'Riverside Lodge No. 10',
                    'role' => 'Member',
                    'status' => 'NPD',
                ],
            ],
        ],
        [
            'member_number' => 'BETA-004',
            'first_name' => 'Richard',
            'last_name' => 'Thomas',
            'birthdate' => '1992-12-18',
            'status' => 'Active',
            'is_active' => true,
            'good_standing' => true,
            'years_in_good_standing' => 3,
            'email' => 'richard.thomas@example.com',
            'affiliations' => [
                [
                    'group_identifier' => 'BETA-LODGE-003',
                    'group_name' => 'Sunset Lodge No. 30',
                    'role' => 'Steward',
                    'status' => 'Active',
                ],
            ],
        ],
    ],
];
